name: Phone RDP

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
      - name: Enable RDP & Firewall
        run: |
          # Enable Remote Desktop and disable NLA
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                           -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                           -Name "UserAuthentication" -Value 0 -Force

          # Allow RDP through firewall
          netsh advfirewall firewall delete rule name="GitHub-RDP" 2>$null
          netsh advfirewall firewall add rule name="GitHub-RDP" dir=in action=allow protocol=TCP localport=3389

          Restart-Service -Name TermService -Force

      - name: Create RDP User (expires in 30 days)
        id: create_user
        run: |
          $upper   = 65..90    | ForEach-Object {[char]$_}
          $lower   = 97..122   | ForEach-Object {[char]$_}
          $number  = 48..57    | ForEach-Object {[char]$_}
          $special = (33..47 + 58..64 + 91..96 + 123..126) | ForEach-Object {[char]$_}
          $allChars = $upper + $lower + $number + $special
          $password = -join ((1..16) | ForEach-Object { $allChars | Get-Random })
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force

          if (Get-LocalUser -Name "RDP" -ErrorAction SilentlyContinue) {
            Set-LocalUser -Name "RDP" -Password $securePass
          } else {
            New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires:$false
          }

          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP" -ErrorAction SilentlyContinue

          $expireDate = (Get-Date).AddDays(30)
          net user RDP /expires:$($expireDate.ToString("MM/dd/yyyy"))

          Add-Content -Path $env:GITHUB_ENV -Value ("RDP_PASSWORD=" + $password)
          Add-Content -Path $env:GITHUB_ENV -Value ("RDP_EXPIRE=" + $expireDate.ToString("o"))

          Write-Host "RDP User: RDP"
          Write-Host "Password: $password"
          Write-Host "Expires: $expireDate"

      - name: Download PageKite
        run: |
          Invoke-WebRequest https://pagekite.net/pk/pagekite.py -OutFile pagekite.py -ErrorAction Stop

      - name: Start PageKite Tunnel
        run: |
          $random = Get-Random -Minimum 10000 -Maximum 99999
          $sub = "rdp-$random"
          Add-Content -Path $env:GITHUB_ENV -Value ("PAGEKITE_SUB=" + $sub)

          # Start PageKite in background
          Start-Process -NoNewWindow -FilePath "python" -ArgumentList "pagekite.py 3389 $sub.pagekite.me" -RedirectStandardOutput pagekite.log
          Start-Sleep -Seconds 15

          Write-Host "=== Connect from Phone ==="
          Write-Host "Host: $sub.pagekite.me"
          Write-Host "Port: 3389"
          Write-Host "Username: RDP"
          Write-Host "Password: $env:RDP_PASSWORD"
          Write-Host "==========================="

      - name: Keep Runner Alive
        run: |
          Write-Host "RDP session active. Keep this workflow running while connecting from phone."
          while ($true) { Start-Sleep -Seconds 300 }
